project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

format:
  html:
    theme:
      light: flatly
      dark: darkly

website: 
  title: "EC327 Game Theory"
  repo-url: https://github.com/dyasui/EC327
  repo-actions: [edit, source, issue]
  favicon: /favicon/favicon.ico
  navbar:
    search: true
    left:
      - text: "Syllabus"
        href: Syllabus/index.qmd
      - text: "Homework"
        href: Homework/index.qmd
      - text: "Slides"
        href: Slides/index.qmd
      - text: "Activities"
        href: activities/index.qmd
      - text: "Exams"
        href: Exams/index.qmd
  sidebar: 
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - section: "Introduction"
        contents:
          - text: "Syllabus"
            href: Syllabus/main.pdf
          - text: "[Slides]{.text-info}: General Principles"
            href: Slides/#intro-and-syllabus-day
          - text: "[Activity]{.text-success}: Guessing Two Thirds"
            href: activities/01GuessTwoThirds/GuessTwoThirds.qmd
      - section: "Sequential Games"
        contents:
          - text: "[Slides]{.text-info}: Sequential Games"
            href: Slides/#sequential-games
          - text: "[Activity]{.text-success}: Survivor Flags"
            href: activities/02SurvivorFlags/SurvivorFlags.qmd
          - text: "[Activity]{.text-success}: Pirate Treasure"
            href: activities/03PirateTreasure/PirateTreasure.qmd
      - section: "Simultaneous Games"
        contents:
          - text: "[Slides]{.text-info}: Simultaneous Games"
            href: Slides/#simultaneous-games
          - text: "[Activity]{.text-success}: Election Blotto"
            href: activities/04BlottoElection/BlottoElection.qmd
          - text: "[Slides]{.text-info}: Continuous Strategies"
            href: Slides/#simultaneous-games
          - text: "[Activity]{.text-success}: Social Media Adspace"
            href: activities/05CournotComp/cournotcomp.qmd
      - section: "Combining Sequential and Simultaneous Forms"
        contents:
          - text: "[Slides]{.text-info}"
            href: Slides/#combining-simultaneous-and-sequential
      - section: "Mixed Strategies"
        contents: 
          - text: "[Slides]{.text-info}"
            href: Slides/#mixed-strategies
          - text: "[Activity]{.text-success}: Penalty Kick Shootout"
            href: activities/06PenaltyKicks/penaltykicks.qmd
      - section: "Uncertainty and Information"
        contents:
          - text: "[Slides]{.text-info}: Asymmetric Information"
            href: Slides/#asymmetric-information
          - text: "**Activity**: Market for Lemons"
            href: activities/LemonsMarket/activitysheet.qmd
      - section: "Strategic Moves"
        contents:
          - text: "[Slides]{.text-info}: Strategic Moves"
            href: Slides/#strategic-moves
          - text: "**Activity**: Brinksmanship"
            href: activities/07Brinksmanship/brinksmanship.qmd
      - section: "Repeated Games"
        contents:
          - text: "[Slides]{.text-info}"
            href: Slides/#repeated-games
  page-footer:
    left: |
      {{< fa regular copyright >}} [Dante Yasui](https://danteyasui.org), 2025 {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)

  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "No class on Wednesday, Nov 26th. Enjoy your Thanksgiving!"
    type: warning
    position: below-navbar
